#!/bin/bash -xe
set -o pipefail

# Enable additional sources
cat > "${root:?}"/etc/apt/sources.list << EOF
deb https://deb.debian.org/debian trixie main contrib non-free non-free-firmware

deb https://deb.debian.org/debian trixie-updates main contrib non-free non-free-firmware

deb https://security.debian.org/debian-security trixie-security main contrib non-free non-free-firmware
EOF

# update/upgrade system
chroot "${root:?}" apt-get update
chroot "${root:?}" apt-get upgrade
