#!/bin/bash -xe
set -o pipefail

packages=(
		btrfs-progs
		cryptsetup
		debootstrap
		dosfstools
		e2fsprogs
		lvm2
		nethack-console
		ostree
		parted
		rsync
		systemd-container
		xfsprogs
	)

chroot "${root:?}" apt-get -y install "${packages[@]}"

echo 'kernel.unprivileged_userns_clone=1' > "${root:?}"/etc/sysctl.d/nspawn.conf
