#!/bin/bash -xe
set -o pipefail

# Append to motd

cat >> "${root:?}"/etc/motd << EOF

${osname:?}/${osversion:?}/${build:?}/${buildenv:?}/${arch:?} (${osdesc:?}) v${version:?}
EOF

# Set hostname
echo "${osname:?}-${osversion:?}-${build:?}-${buildenv:?}" > "${root:?}"/etc/hostname
echo "127.0.1.1 ${osname:?}-${osversion:?}-${build:?}-${buildenv:?}" >> "${root:?}"/etc/hosts
echo "Etc/UTC" > "${root:?}"/etc/localtime
